origin: https://localhost
port: 3000
allowSignUp: true

mariadb:
  host: db
  port: 3306
  username: traq
  password: password
  database: traq

es:
  url: http://es:9200
  username: elastic
  password: password

storage:
  type: local
  local:
    dir: /app/storage

