name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Checkout And Build
        run: docker compose up -d
      - name: healthcheck front
        run: curl -k -s https://localhost:8080 || exit 1
      - name: healthcheck backend
        run: curl -k -s https://localhost:8080/api/v3/version || exit 1
    
