name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Checkout And Build
        run: docker compose up --quiet-pull -d 
      - name: healthcheck front
        run: docker compose exec es curl -k http://frontend:80 || exit 1
      - name: healthcheck backend
        run: docker compose exec es curl -k http://backend:3000/api/v3/version || exit 1
    
